ministryofjustice/opg-performance-data

use-an-lpa/data.json
also corrected previous months
=> UML-1633 - July data

make-a-lpa/data.json
Figures have already been entered for up to and including October 2021 but need amending from July 2021. November figure to be added too.
- July 2021 - 92%
- August 2021 - 92%
- September 2021- 91%
- October 2021 - 92%
- November 2021- 92%
=> LPAL-635 - Amend & add satisfaction scores

use-an-lpa/data.json
=> UML-1944 - add november 2021 stats

.github/workflows/validate.yml, make-a-lpa/data.json, schema.json
Adds a schema check to ensure data added is valid before merging to main.
=> Add github action to validate JSON files

use-an-lpa/data.json
https://opgtransform.atlassian.net/browse/UML-2068
=> UML-2068 - add December and January data

make-a-lpa/data.json
Add performance data for make-a-lpa for Feb-June 2022; partial data only for June.
=> LPAL-834 Add make-a-lpa performance data to June 2022

make-a-lpa/data.json
Stats were incorrectly edited for LPAL-834, so rectify errors.
=> Fix performance stats for make-a-lpa -> June 2022

README.md
https://github.com/orgs/ministryofjustice/teams/operations-engineering/discussions
=> Update MoJ Compliance badge

src/_data/make_a_lpa/data.json
See [LPAL-1007](https://opgtransform.atlassian.net/browse/LPAL-1007) for the source stats.
=> LPAL-1007 Update perf stats for Make an LPA

.github/workflows/build_deploy_workflow.yml, .github/workflows/pr_workflow.yml, renovate.json
Simplify renovate config using defaults for updates
Add yarn node_modules cache for faster builds
=> Renovate config actions cache

renovate.json
Enable lockfile maintenance via renovate
=> Enable lockfile maintenance via renovate

src/_includes/budget.json
Based on first run of the budget check, updates the figures to match them
=> Update lighthouse budget with new figures

renovate.json
- Ignore dependencies until 3 days old
- Disable lockfile maintenance
- Group patch/minor
- Auto merge patch/minor
- Individual PRs for Major
- No automerge for Major PRs
=> Update renovate configuration to match OPG standards

src/_data/make_a_lasting_power_of_attorney_service/data.json, src/_data/use_a_lasting_power_of_attorney_service/data.json
UML-2874 Latest stats for Use and Make
=> UML-2874 latest stats for Use and Make

src/_data/make_a_lasting_power_of_attorney_service/data.json
Now includes April,  and updates to digital take-up for previous months after backlog cleared
=> LPAL-1221 updated stats

.github/workflows/pr_workflow.yml, .pre-commit-config.yaml, CODEOWNERS, schema.json, src/_data/complete_the_deputy_report_service/README.md, src/_data/complete_the_deputy_report_service/data.json, src/_includes/layouts/base.njk, src/_includes/partials/navigation.njk, src/complete-the-deputy-report-service/index.njk, src/index.njk, validate/index.js
Adds Digideps to the site. All links and schema validation is updated.
=> DDPD-4057 add digideps to performance site

src/_data/make_a_lasting_power_of_attorney_service/data.json, src/_data/use_a_lasting_power_of_attorney_service/data.json
UML-2943 June stats for Make and Use
=> UML-2943 June stats for Make and Use

src/_data/make_a_lasting_power_of_attorney_service/data.json, src/_data/use_a_lasting_power_of_attorney_service/data.json
Fixes UML-2894
July stats for make and use.
=> Update make/use with July numbers

README.md, src/_data/complete_the_deputy_report_service/data.json
=> Adding in 09/23 data for complete the deputy report, and updating readme

src/_data/make_a_lasting_power_of_attorney_service/data.json, src/_data/use_a_lasting_power_of_attorney_service/data.json
=> UML-3157 stats for oct 23

src/_data/complete_the_deputy_report_service/data.json
Updating Performance Data for complete_the_deputy_report for year and month 24_02
=> Performance Data for complete_the_deputy_report 24_02

src/_data/complete_the_deputy_report_service/data.json
Updating Performance Data for complete_the_deputy_report for year and month 24_03
=> Performance Data for complete_the_deputy_report 24_03

src/_data/complete_the_deputy_report_service/data.json
Updating Performance Data for complete_the_deputy_report for year and month 24_04
=> Performance Data for complete_the_deputy_report 24_04

src/_data/make_a_lasting_power_of_attorney_service/data.json, src/_data/use_a_lasting_power_of_attorney_service/data.json, src/_includes/budget.json
UML-3475 stats up to June 24.  Give lighthouse test slightly longer timeout so builds don't break
=> UML-3475 stats up to June 24

src/_data/make_a_lasting_power_of_attorney_service/data.json, src/_data/use_a_lasting_power_of_attorney_service/data.json
Jul and Aug stats for Use and Make
=> jul and aug stats

src/_data/complete_the_deputy_report_service/data.json, validate/index.js
Changed the code that generates this on digideps side.
=> DDLS-580 use - instead of _ for dataType values

src/make-a-lasting-power-of-attorney-service/index.njk
At request of @jrattle , add the breakdown of satisfaction numbers to the template for Make, like is already reported for Use
=> UML-3951 add fields to Make data
